import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { verifyToken } from '@/lib/auth';
import path from 'path';
import { readFile, writeFile } from 'fs/promises';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

const UPLOADS_DIR = path.join(process.cwd(), 'uploads');

function getAuthUser(req: NextRequest) {
  const authHeader = req.headers.get('authorization');
  if (!authHeader?.startsWith('Bearer ')) return null;
  return verifyToken(authHeader.slice(7));
}

export async function GET(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const payload = getAuthUser(req);
    if (!payload) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const { id } = await params;
    const doc = await db.document.findFirst({
      where: { id, ownerId: payload.userId as string },
      include: {
        signers: { orderBy: { order: 'asc' } },
        auditLogs: { orderBy: { createdAt: 'asc' } },
      },
    });

    if (!doc) return NextResponse.json({ error: 'Document not found' }, { status: 404 });
    if (doc.status !== 'Completed') {
      return NextResponse.json({ error: 'Certificate only available for completed documents' }, { status: 400 });
    }

    // Generate completion certificate PDF
    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const page = pdfDoc.addPage([612, 792]);
    const { width, height } = page.getSize();

    // Header
    page.drawText('CERTIFICATE OF COMPLETION', { x: 50, y: height - 50, size: 24, font: fontBold, color: rgb(0.02, 0.59, 0.41) });
    page.drawLine({ start: { x: 50, y: height - 60 }, end: { x: width - 50, y: height - 60 }, thickness: 2, color: rgb(0.02, 0.59, 0.41) });

    let y = height - 100;
    const drawLine = (text: string, size = 11) => {
      page.drawText(text, { x: 50, y, size, font, color: rgb(0.15, 0.15, 0.15) });
      y -= size + 6;
    };
    const drawBold = (text: string, size = 12) => {
      page.drawText(text, { x: 50, y, size, font: fontBold, color: rgb(0.1, 0.1, 0.1) });
      y -= size + 6;
    };

    drawLine(`Document: ${doc.title}`, 13);
    drawLine(`Document ID: ${doc.id}`);
    drawLine(`Created: ${new Date(doc.createdAt).toLocaleString()}`);
    drawLine(`Completed: ${doc.signedPdfPath ? new Date(doc.updatedAt).toLocaleString() : 'N/A'}`);
    y -= 10;

    drawBold('Signers:');
    for (const signer of doc.signers) {
      drawLine(`  ${signer.name} (${signer.email})`);
      drawLine(`    Signed: ${signer.signedAt ? new Date(signer.signedAt).toLocaleString() : 'Pending'}`);
      if (signer.rejectionReason) {
        drawLine(`    Rejected: ${signer.rejectionReason}`);
      }
    }
    y -= 10;

    drawBold('Audit Trail:');
    for (const log of doc.auditLogs.slice(0, 20)) {
      const time = new Date(log.createdAt).toLocaleString();
      drawLine(`  [${time}] ${log.action}`);
      if (log.details) drawLine(`    ${log.details.substring(0, 80)}`);
      if (log.ipAddress) drawLine(`    IP: ${log.ipAddress}`);
    }

    // Footer
    y -= 20;
    page.drawLine({ start: { x: 50, y }, end: { x: width - 50, y }, thickness: 1, color: rgb(0.8, 0.8, 0.8) });
    y -= 20;
    page.drawText('This certificate was automatically generated by OpenSign.', { x: 50, y, size: 9, font, color: rgb(0.5, 0.5, 0.5) });
    page.drawText(`Generated: ${new Date().toISOString()}`, { x: 50, y: y - 14, size: 9, font, color: rgb(0.5, 0.5, 0.5) });
    page.drawText('ESIGN Act / eIDAS Compliant', { x: 50, y: y - 28, size: 9, font, color: rgb(0.5, 0.5, 0.5) });

    const pdfBytes = await pdfDoc.save();
    const certPath = `certificate-${doc.id}.pdf`;
    await writeFile(path.join(UPLOADS_DIR, certPath), pdfBytes);

    await db.document.update({ where: { id }, data: { certificatePath: certPath } });

    const fileBuffer = await readFile(path.join(UPLOADS_DIR, certPath));
    return new NextResponse(fileBuffer, {
      headers: { 'Content-Type': 'application/pdf', 'Content-Disposition': `attachment; filename="certificate-${doc.title}.pdf"` },
    });
  } catch (error) {
    console.error('Certificate error:', error);
    return NextResponse.json({ error: 'Failed to generate certificate' }, { status: 500 });
  }
}